## explore catalyst API data feeds

In [ ]:
import requests
import pandas as pd

url = f"https://api.biopharmcatalyst.com/api/user/v1/historical-catalysts?key={api_key}"

response = requests.get(url)
data = response.json()

print(data)
data = pd.DataFrame(data)

NameError: name 'api_key' is not defined

In [ ]:
data.head()

,nct_number,company_name,company_ticker,conference_acronym,conference_end_date,conference_link,conference_name,conference_start_date,date,drug_name,indication,label,press_link,catalyst,stage,statuses
0,NCT05225584,Kymera Therapeutics Inc.,KYMR,None,None,None,None,None,2023-06-14,KT-333 - (STAT3),Peripheral T-cell Lymphoma (PTCL),Phase 1a,https://www.biopharmcatalyst.com/company/KYMR/...,Phase 1a data continue to demonstrate robust d...,Phase 1a,[{'label': 'Orphan Drug Designation (ODD)'}]
1,NCT05225584,Kymera Therapeutics Inc.,KYMR,None,None,None,None,None,2023-12-10,KT-333 - (STAT3),Peripheral T-cell Lymphoma (PTCL),Phase 1a,https://www.biopharmcatalyst.com/company/KYMR/...,Additional data presented at ASH reported that...,Phase 1a,[{'label': 'Orphan Drug Designation (ODD)'}]
2,NCT04830137,Nurix Therapeutics Inc.,NRIX,None,None,None,None,None,2022-10-26,Zelebrudomide (NX-2127),"B-cell malignancies, chronic lymphocytic leuke...",Phase 1a,https://www.biopharmcatalyst.com/company/NRIX/...,Phase 1a extension in CLL data reported meanin...,Phase 1a,[]
3,None,INmune Bio Inc.,INMB,None,None,None,None,None,2023-11-01,INKmune,Myelodysplastic syndromes (MDS),Phase 1a,https://inmunebio.com/tmp/b98d61cdf1d9a4e1b8c2...,Open-label Phase I data reported that INKmune ...,Phase 1a,[]
4,NCT04136873,AbbVie Inc.,ABBV,None,None,None,None,None,2022-12-19,Emraclidine (CVL-231) - (EMPOWER-1),Schizophrenia,Phase 1,https://www.biopharmcatalyst.com/company/CERE/...,Phase 1 results reported that treatment demons...,Phase 1,[]

In [ ]:
data['date'] = pd.to_datetime(data['date'])
data = data[data['date']>='2021-01-01']
data = data[data['date']<='2026-06-30']

In [ ]:
keptColumns = ['catalyst',
               'date',
               'company_name',
               'company_ticker',
               'drug_name',
               'nct_number',
               'label',
               'press_link',
               'stage']

catalyst_features = data.reindex(columns = keptColumns)

In [ ]:
data.head(1)
catalyst_features.head()

,catalyst,date,company_name,company_ticker,drug_name,nct_number,label,press_link,stage
0,Phase 1a data continue to demonstrate robust d...,2023-06-14,Kymera Therapeutics Inc.,KYMR,KT-333 - (STAT3),NCT05225584,Phase 1a,https://www.biopharmcatalyst.com/company/KYMR/...,Phase 1a
1,Additional data presented at ASH reported that...,2023-12-10,Kymera Therapeutics Inc.,KYMR,KT-333 - (STAT3),NCT05225584,Phase 1a,https://www.biopharmcatalyst.com/company/KYMR/...,Phase 1a
2,Phase 1a extension in CLL data reported meanin...,2022-10-26,Nurix Therapeutics Inc.,NRIX,Zelebrudomide (NX-2127),NCT04830137,Phase 1a,https://www.biopharmcatalyst.com/company/NRIX/...,Phase 1a
3,Open-label Phase I data reported that INKmune ...,2023-11-01,INmune Bio Inc.,INMB,INKmune,None,Phase 1a,https://inmunebio.com/tmp/b98d61cdf1d9a4e1b8c2...,Phase 1a
4,Phase 1 results reported that treatment demons...,2022-12-19,AbbVie Inc.,ABBV,Emraclidine (CVL-231) - (EMPOWER-1),NCT04136873,Phase 1,https://www.biopharmcatalyst.com/company/CERE/...,Phase 1

In [ ]:
max(catalyst_features['date'])

Timestamp('2026-06-30 00:00:00')